<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIfiSCp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIfiSCp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIfiSCp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIfiSCp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXIfiSCp\App_KernelDevDebugContainer([
    'container.build_hash' => 'XIfiSCp',
    'container.build_id' => '70230e77',
    'container.build_time' => 1590500136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIfiSCp');
