<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4T0vu7g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4T0vu7g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4T0vu7g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4T0vu7g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4T0vu7g\App_KernelDevDebugContainer([
    'container.build_hash' => '4T0vu7g',
    'container.build_id' => '725d836b',
    'container.build_time' => 1590504765,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4T0vu7g');
