<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWupg7OF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWupg7OF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWupg7OF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWupg7OF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWupg7OF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wupg7OF',
    'container.build_id' => '6b28051e',
    'container.build_time' => 1590495718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWupg7OF');
